// src/core/ai/fill.ts
import { describeReason } from '../errorReason.js';
import { ValidationError } from '../errors.js';
import { expectedButEmptyNote } from '../extract/rows.js';
import type { Column, DocumentData, ExtractedRow, Profile, Transform } from '../extract/types.js';
import { eligibleColumns } from './eligible.js';
import { buildPrompt, cleanReply } from './prompt.js';
import { assertUsableBudget, sliceForModel, type SliceShape } from './slice.js';
import { unsupportedClaims, type UnsupportedClaim } from './verify.js';

/**
 * Just enough of a provider to be substitutable in a test.
 *
 * ## AN IMPLEMENTER'S OBLIGATION: EVERY MESSAGE THIS THROWS IS ALREADY REDACTED
 *
 * Not a note about `OpenAiCompatibleProvider` -- a condition of implementing
 * this interface, stated here because this is the file a second adapter's
 * author reads. **`fill.ts` writes the reason for a failed call straight into a
 * spreadsheet note**, and a spreadsheet is a file operators email around asking
 * for help. An API key that reaches one is a key disclosed.
 *
 * It covers the WHOLE CAUSE CHAIN, not the top message. `describeReason` walks
 * `cause` -- it has to, because Node's own `fetch` throws `TypeError: fetch
 * failed` and hides the useful half underneath -- so an adapter that writes the
 * ordinary `new Error(message, { cause: rawFetchError })` hands an unredacted
 * chain to a note. `OpenAiCompatibleProvider` meets this by redacting BEFORE
 * truncating (the other order leaves a matchable fragment and lets a prefix
 * walk out) and by deliberately attaching no `cause` at all, since redaction
 * cannot reach inside an object it did not build. An adapter that needs a cause
 * must build one it has redacted itself.
 *
 * The second condition is smaller and in the same spirit: a failure throws,
 * always, and never returns an empty string. A caller that cannot tell "the
 * model said nothing" from "the call failed" writes a blank and calls it
 * success -- the exact shape of failure this codebase has shipped repeatedly.
 */
export interface Completer {
  complete(prompt: string): Promise<string>;
}

export interface FillOptions {
  /** Characters of document to send. See `slice.ts`. */
  budget: number;
  /** Section headings to prefer when the whole document will not fit. */
  sections: string[];
  /**
   * Most REQUESTS to make in one run. Reaching it is reported, never silent.
   *
   * Requests, not rows: a row with two enabled columns is two calls and two
   * lots of spend, and counting rows would let a cap of 500 make a thousand
   * calls. With one column enabled -- what ships -- the two numbers happen to
   * be equal, and NOTHING RELIES ON THAT. `confirm.ts` states every figure in
   * requests rather than documents, precisely so the wording stays true the
   * moment a profile enables a second column. An earlier version of this
   * comment said the dialog "can go on saying documents"; it does not, and
   * that sentence outlived the code it described.
   */
  cap: number;
  /**
   * The model that is answering, by the name it has at its endpoint.
   *
   * REQUIRED, AND ITS ONE READER IS THE DISCLOSURE. `Profile.aiProvenance` may
   * substitute it into a note that goes into the ITEM -- the only thing this
   * pass writes that survives `plan.ts` dropping the annotation columns, and so
   * the only way a future reader of the catalogue learns a machine wrote the
   * record. A profile that asks "generated by {model}" and is handed nothing
   * discloses "generated by ", which is worse than not disclosing at all.
   *
   * An earlier task removed this field as unused and recorded that it earns its
   * place here. It does not reach the prompt: the model has no need to be told
   * its own name, and `provider.ts` already puts it in the request body.
   */
  model: string;
  /** House style, from the profile. */
  instruction?: string | null;
}

export interface FillTarget {
  row: ExtractedRow;
  doc: DocumentData;
}

/**
 * Refuse a run cap nothing sensible can be counted against.
 *
 * A NaN cap is the worse of the two configuration faults this pass can carry:
 * it compares false against everything, so `used >= cap` never fires, the
 * ceiling the operator agreed to silently does not exist, and every row in the
 * batch is sent to a paid endpoint.
 *
 * EXPORTED SO THE SETTINGS STORE CAN ASK BEFORE ANYTHING IS SAVED, for the same
 * reason `assertUsableBudget` is (see slice.ts). A mistyped box should be
 * refused on the screen where it was typed, not four hundred rows into a run --
 * and the two answers cannot disagree if there is only one of them. A second
 * copy on the way in is free to drift from the one that actually runs, which
 * would let the settings screen accept a value the run then refuses.
 *
 * ZERO IS ALLOWED, and is not the same as a mistake: it means "make no requests
 * at all", every row says it was stopped by the limit, and nothing is spent.
 */
export function assertUsableCap(cap: number): void {
  if (!Number.isFinite(cap) || cap < 0) {
    throw new ValidationError(
      `The model run limit must be zero or a positive number, but it was '${String(cap)}'. ` +
        `It is the most requests one run may make; nothing beyond it is sent, and every row it stops says so.`,
    );
  }
}

/**
 * Say, on every cell that wanted a model and could not have one, that there was
 * none -- the counterpart to `fillWithModel`, for the case where it is not run.
 *
 * ## The cell must not simply come out blank
 *
 * A column that asked for a model at an institution that configured none
 * produces an empty cell, and an empty cell is indistinguishable from a document
 * that had nothing to say. That is a thing which could not run being reported as
 * if it had, and it is the failure this codebase has shipped four times: a
 * successful-looking result from a check that never happened.
 *
 * ## Per cell, naming the column
 *
 * One warning on the batch cannot say WHICH of a profile's columns was left
 * unfilled, and an operator scanning `_notes` for a row is looking for the
 * column name. The grammar is `${path}: `, the same prefix `rows.ts#fill` and
 * every note in this module use, so a column is found the same way in all of
 * them.
 *
 * ## Only cells the model would actually have been asked about
 *
 * `eligibleColumns`, not `modelColumns`: a cell a document already filled would
 * never have been sent, so announcing a missing model there is noise on a row
 * where nothing is missing. This is the same rule the fill pass runs, asked of
 * the same finished row, so the two cannot disagree about which cells were in
 * play.
 *
 * NOT RECORDED IN `aiWritten`, deliberately. That map is what `review.ts`
 * subtracts to tell a routine model write from a real problem, and this IS a
 * real problem: a column asked for a value and did not get one, so the row must
 * keep counting as needing review.
 */
export function noteMissingModel(
  rows: ExtractedRow[],
  profile: Profile,
  reason: MissingModelReason,
): void {
  for (const row of rows) {
    for (const path of eligibleColumns(profile, row)) {
      row.notes.push(`${path}: ${MISSING_MODEL[reason]}`);
    }
  }
}

/**
 * Why no model filled a cell that asked for one.
 *
 * THREE DIFFERENT EVENTS, THREE DIFFERENT SENTENCES, and the reason this is an
 * argument rather than a constant is that they were briefly one sentence. An
 * operator who has `OEQ_MODEL_BASE_URL` and `OEQ_MODEL` set and merely forgot
 * `--ai` was told, four hundred times, that no model is configured, and pointed
 * at the two variables they had already set. The remedy was never mentioned.
 *
 * That is this codebase's named failure shape -- a diagnosis naming the one
 * place the problem is not -- and it had a test pinning it, so nobody would have
 * noticed.
 */
export type MissingModelReason = 'not-configured' | 'not-requested' | 'not-approved';

const MISSING_MODEL: Record<MissingModelReason, string> = {
  'not-configured':
    `no model is configured, so nothing was written here. ` +
    `Set one up on the Setup screen, or with OEQ_MODEL_BASE_URL and OEQ_MODEL from the ` +
    `command line -- or fill this cell in by hand.`,
  'not-requested':
    `this column asks for a language model, and --ai was not given, so nothing was written ` +
    `here. Re-run with --ai to fill it -- or fill this cell in by hand.`,
  'not-approved':
    `no model was run for this batch, so nothing was written here. If you expected one, ` +
    `check the model settings for this site on the Setup screen -- or fill this cell in by hand.`,
};

/**
 * The section headings a profile already knows about, for `slice.ts` to prefer
 * when a document will not fit whole.
 *
 * READ FROM THE PROFILE RATHER THAN ASKED FOR SEPARATELY. A `{ section: 'Abstract' }`
 * source is the operator saying "this collection's documents put the interesting
 * part under this heading" -- which is precisely the question the slice needs
 * answered, and they have already answered it. A second setting would be one more
 * box to fill in correctly, empty on every profile written before it existed, and
 * free to drift out of step with the sources beside it.
 *
 * Deduplicated and in profile order, so a document is sliced the same way twice.
 */
export function modelSections(profile: Profile): string[] {
  const headings = new Set<string>();
  for (const column of profile.columns) {
    for (const source of column.sources) {
      if ('section' in source) headings.add(source.section);
    }
  }
  return [...headings];
}

/**
 * What is written into `_source` for a cell a model wrote.
 *
 * SET HERE RATHER THAN THROUGH `rows.ts#sourceKind`, which has no `ai` case and
 * would fall through to `properties` -- naming an embedded document property as
 * the origin of something no document contains. That function is unreachable
 * from this pass by design: `resolve` returns empty for an `ai` source and
 * never records a kind for it, so the marker has exactly one home and this is
 * it.
 */
const AI_SOURCE = 'ai';

/**
 * What is written into `_source` for the provenance cell.
 *
 * DISTINCT FROM `ai`, and the distinction is not pedantry: no model wrote that
 * text. The profile author did, and this tool stamped it with a model's name. A
 * reviewer sorting the spreadsheet by `_source` to read everything a machine
 * composed would otherwise be handed a sentence they wrote themselves.
 */
const PROVENANCE_SOURCE = 'ai-provenance';

/** Most of a discarded reply to quote back, in code points. Enough to recognise
 *  a refusal or a stray preamble; not enough to paste a generated paragraph
 *  into a cell somebody has to read. */
const MAX_QUOTED_REPLY = 80;

/**
 * Text safe to put in one spreadsheet cell.
 *
 * APPLIED TO EVERY UNTRUSTED STRING THIS MODULE WRITES, and the reason is
 * sharper for the error path than for the model's reply: `describeReason`
 * returns up to 200 characters that may have come from a SERVER'S RESPONSE
 * BODY, so it is the one carrying text nobody here chose. A newline in it ends
 * the note visually; a control character can be invisible in the cell and
 * present in the file.
 *
 * `\s` alone is not enough -- it misses the C0 controls a truncated or binary
 * response is full of -- so the class covers `\p{Cc}` and `\p{Cf}` too, which
 * needs the `u` flag.
 */
function flatten(text: string): string {
  return text.replace(/[\p{Cc}\p{Cf}\s]+/gu, ' ').trim();
}

/**
 * Which kind of value a column holds, where the profile says so.
 *
 * THE SPEC REQUIRES THE FLAG TO SAY WHICH KIND OF FIELD IT WAS. "A description
 * that reads oddly is a quality problem a cataloguer can fix. A fabricated
 * death date is indistinguishable from a real one to everyone downstream,
 * permanently", in a collection with no moderation queue.
 *
 * DERIVED FROM THE PROFILE, NEVER A NEW SETTING. A per-column `factField` flag
 * would be one more thing to set correctly, wrong by default on every profile
 * written before it existed, and free to drift out of step with the column it
 * describes. Two things a column already declares say this without being asked:
 * a `transform`, which exists precisely because the value is a date or a list
 * of people; and a `dateNear`/`datePair` source, which is a column asking for a
 * date whether or not it also declared a transform -- the shipped obituary
 * template's death-date column is sourced exactly that way.
 *
 * THE TRANSFORM ARM IS EXHAUSTIVE ON PURPOSE. Written as a catch-all --
 * `transform !== undefined ? 'date'` -- a `transform: 'uppercase'` added later
 * would make every such column announce "this column holds a date. An invented
 * date cannot be told from a real one", which is a false statement inside the
 * one note whose entire job is to say which kind of field it was. `rows.ts` has
 * the loud version of this already: it narrows the same way and then reads
 * `.date`, so a new member breaks the typecheck there. This does the same with
 * a `never` assignment.
 *
 * WHAT IT MISSES, AND THIS IS NOT SMALL:
 *
 * - **Fact fields that declare nothing.** An identifier, a place name, a term
 *   from a controlled vocabulary, a person's name recorded as plain text. All
 *   are fact fields by the spec's definition -- "dates, names, identifiers,
 *   anything from a controlled vocabulary" -- and none of them declares
 *   anything this function can read, so each gets the prose wording.
 * - **Future date-shaped sources.** The `dateNear`/`datePair` arm is a literal
 *   list with no typecheck behind it, because `Source` is a union of object
 *   shapes rather than a tagged enum. A `{ dateRange: ... }` added later is
 *   silently prose, and nothing fails to tell anyone.
 *
 * The failure is in the safe direction -- every model-written cell is flagged
 * regardless; a fact field is merely flagged less loudly -- and the alternative
 * was a list of xpath substrings such as `identifier`, which is guessing at an
 * institution's schema, the assumption an entire release was spent removing. If
 * this must be closed, close it by giving the profile something honest to
 * declare, not by pattern matching on somebody else's field names.
 */
function factKind(column: Column): 'date' | 'name' | null {
  const fromTransform = (transform: Transform): 'date' | 'name' => {
    if (transform === 'people') return 'name';
    if (transform === 'date') return 'date';
    if (typeof transform === 'object' && 'date' in transform) return 'date';
    // Unreachable while `Transform` holds only the members above; a new one
    // stops the build here rather than being announced to an operator as a
    // date. Named so the compiler's message says what to do.
    const everyTransformIsClassified: never = transform;
    return everyTransformIsClassified;
  };

  if (column.transform !== undefined) return fromTransform(column.transform);
  if (column.sources.some((s) => 'dateNear' in s || 'datePair' in s)) return 'date';
  return null;
}

/**
 * The note left on a cell the model wrote.
 *
 * EVERY WRITE IS FLAGGED, without exception -- a model output is a guess, and
 * this tool's rule is that a guess says so. A fact field says more than that,
 * because the two are not the same risk and a reviewer skimming four hundred
 * notes needs the difference visible on the line.
 *
 * `${path}: ` is the pipeline's own prefix, from `rows.ts#fill`. One grammar
 * for every per-column note, so the column can be found the same way in all of
 * them.
 */
function writtenNote(column: Column, path: string): string {
  const kind = factKind(column);
  if (kind === null) {
    return `${path}: written by a language model from the document text -- please check it before uploading.`;
  }
  return (
    `${path}: written by a language model from the document text, and this column holds a ${kind}. ` +
    `An invented ${kind} cannot be told from a real one by anyone reading the catalogue afterwards, ` +
    `so check it against the document before uploading.`
  );
}

/**
 * One clause saying the model did not see the whole file, or nothing.
 *
 * ONE CLAUSE ON THE EXISTING NOTE, never a second note per cell: a batch of 400
 * rows carrying two notes each is a wall nobody reads, and the first thing to
 * be skipped in a wall is the flag that matters. Added to a failure note as
 * well as to a write -- a refusal from a model that saw a fifth of the document
 * is exactly the surprising output the recorded shape exists to explain.
 */
function sentClause(shape: SliceShape): string {
  return shape === 'whole'
    ? ''
    : ' Only part of the document was sent: its opening and any named sections, not all of it.';
}

/**
 * A reply the cleaner threw away, quoted back, or nothing.
 *
 * THE MODEL SPOKE AND THIS TOOL BINNED IT. A note saying only "the model
 * declined" is true; a note that leaves the operator unable to see there was an
 * answer at all is the same misreport this codebase keeps shipping, wearing its
 * other face. Both discards -- the refusal pattern and the preamble pattern --
 * are heuristics their own docblocks admit can be wrong, so the operator is
 * given enough of the reply to judge whether the cleaner was right.
 *
 * TRUNCATED, AND SAFE TO SHOW. It goes into `_notes`, which `plan.ts` drops
 * with every other annotation column before anything is uploaded, so a refusal
 * quoted here cannot reach a catalogue record the way one written into the cell
 * would. Cut BY CODE POINT: cutting a UTF-16 string at 80 units can split a
 * surrogate pair and leave a lone half, which is not a character and does not
 * survive a round trip through a spreadsheet.
 */
function quoted(discarded: string): string {
  const flat = flatten(discarded);
  if (flat === '') return '';
  const points = [...flat];
  const shown =
    points.length > MAX_QUOTED_REPLY
      ? `${points.slice(0, MAX_QUOTED_REPLY).join('')}...`
      : flat;
  return ` What it said, which was not used: "${shown}"`;
}

/**
 * Why a reply was thrown away for stating what the document does not.
 *
 * ## A FOURTH EVENT, AND IT MUST NOT WEAR ANY OF THE OTHER THREE FACES
 *
 * This module already distinguishes a failed call, a reply the cleaner
 * discarded, and a row nothing was sent for. A refusal is none of them: the call
 * SUCCEEDED, the model ANSWERED, the answer was well formed, and this tool
 * declined it. An operator told "the model gave no answer" would go and look at
 * the model, which is the diagnosis-naming-the-one-place-the-problem-is-not
 * failure this codebase has a name for. So the note says refused, says the model
 * did answer, and says there is nothing to retry.
 *
 * ## IT NAMES EVERY FAILED CLAIM, WITH THE REASON BESIDE IT
 *
 * The operator's next action is to go to the document and look, and "some claim
 * was unsupported" does not say what to look for. `claim` is the model's own
 * wording so it can be found in the quoted reply, and `why` is the check's
 * finding about that one claim -- a date the document never states reads
 * differently from a date the document states less precisely, and the second is
 * a hint about where to look.
 *
 * `flatten` on the claim for the same reason the reason string gets it: it is
 * model output, and a control character is invisible in a spreadsheet cell and
 * present in the file.
 */
function refusalNote(path: string, outcome: string, claims: UnsupportedClaim[]): string {
  const listed = claims.map((claim) => `"${flatten(claim.claim)}": ${claim.why}.`).join(' ');
  return (
    `${path}: ${outcome} -- the model's answer was refused, because it stated things this ` +
    `document does not support. ${listed} The model did answer and the call succeeded -- this ` +
    `tool discarded the answer -- so there is nothing to retry; read the document and fill this ` +
    `cell in by hand.`
  );
}

/**
 * Fill eligible cells from a language model. Mutates the rows in place, the way
 * the rest of the extract pipeline already works.
 *
 * ONE CALL PER ELIGIBLE CELL, IN ORDER, AND NEVER A RETRY. A retry loop over a
 * paid endpoint is a bill nobody agreed to, and the operator has already been
 * shown a count and confirmed it. A failure leaves the cell as it found it,
 * with the reason on the row.
 *
 * EVERY WRITE IS FLAGGED. A model output is a guess, and this tool's rule is
 * that a guess says so -- the same rule that flags an opening paragraph.
 *
 * NOTHING IS EVER WRITTEN EXCEPT AN `ok` REPLY. A refusal, a preamble with
 * nothing under it, an empty answer and a failed call all leave the cell
 * exactly as they found it and say what happened. `cleanReply` carries no
 * `text` on a failure precisely so this cannot be got wrong by accident.
 *
 * RUNNING IT TWICE OVER THE SAME ROWS SENDS NOTHING THE SECOND TIME. A written
 * cell is no longer eligible, because the write clears the flag that made it
 * eligible and records itself in `aiWritten` instead. Without that, a second
 * pass re-sends and re-charges for every cell the first one wrote, and
 * overwrites the model's own earlier answer with a different one.
 */
export async function fillWithModel(
  targets: FillTarget[],
  profile: Profile,
  provider: Completer,
  options: FillOptions,
): Promise<void> {
  // BEFORE THE LOOP, BOTH OF THEM. A mistyped budget or cap is a configuration
  // fault affecting every row identically, and a run that discovers it per row
  // produces four hundred notes about a single text box -- after spending
  // nothing, while looking like it tried. A NaN cap is the worse of the two: it
  // compares false against everything, so the ceiling the operator agreed to
  // silently does not exist and every row is sent.
  assertUsableBudget(options.budget);
  assertUsableCap(options.cap);

  let used = 0;

  for (const { row, doc } of targets) {
    const eligible = new Set(eligibleColumns(profile, row));
    // Before the document is touched at all: a row with nothing to fill must
    // not pay to read, slice or measure a file nobody is going to send.
    if (eligible.size === 0) continue;

    // SLICED ONCE PER ROW, not once per eligible column. The slice depends on
    // the document alone, so computing it per column repeats the whole of
    // `slice.ts` -- two section scans and a two-pass budget division -- to
    // produce the identical string, once per enabled field on every row in the
    // batch. Nothing asserts the count, deliberately: reads of `doc.text` are
    // not the same thing as calls to `sliceForModel`, and a test that watched
    // them would pass a mutation that sliced per column while failing a
    // harmless inlining. What IS asserted is that both columns are sent the
    // same document.
    const text = doc.text;
    const slice = sliceForModel(text, { budget: options.budget, sections: options.sections });

    if (slice.shape === 'empty') {
      // The one cause that is knowable, told apart from the two that are not.
      // See `SliceShape`: an empty slice also arises from a document with no
      // opening and no named section, and from a budget too small for any part
      // to survive -- and sending the operator to the file when the fault is a
      // setting is the same wrong-cause defect in a new place.
      const why =
        text.trim() === ''
          ? 'this file has no text to read.'
          : `nothing could be selected to send within the character budget of ${options.budget}. ` +
            `Raising the budget may fix it; the document may also have no opening paragraph and ` +
            `none of the named sections.`;
      for (const path of eligible) row.notes.push(`${path}: not sent to the model -- ${why}`);
      // No call was made, so no cap was spent. A row that could not be sent
      // must not consume the ceiling a row that can be sent needs.
      continue;
    }

    // ONE PER ROW, NOT ONE PER CELL. See `discloseInItem`.
    let wroteSomething = false;

    // Over the COLUMNS rather than the paths, so the column each path belongs
    // to needs no lookup. The lookup it replaces could not fail -- every path
    // came from `profile.columns` -- but its `undefined` branch had to do
    // something, and every option was wrong: skipping silently leaves a cell
    // with neither a value nor a note, which is the one failure mode this
    // module is otherwise careful about.
    for (const column of profile.columns) {
      if (!eligible.has(column.path)) continue;
      const path = column.path;

      if (used >= options.cap) {
        row.notes.push(
          `${path}: not sent to the model -- this run reached its limit of ${options.cap} model requests.`,
        );
        continue;
      }
      // Counted before the call, not after it: a call that throws still cost
      // whatever the endpoint charged for accepting it.
      used += 1;

      // WHICH FAILURE SENTENCE IS TRUE DEPENDS ON WHAT IS IN THE CELL. The
      // eligible set is "empty OR flagged", so on the design's headline case --
      // tier 3 produced a flagged opening paragraph and the model was invited
      // to improve on it -- the cell still holds that paragraph. Keeping it is
      // right; blanking it would destroy evidence the design says may only be
      // replaced by something better. But "was left blank" is then false: an
      // operator filtering `_notes` for it gets rows that are not blank, and
      // one skimming reads a populated description as absent.
      const outcome = (row.cells[path] ?? '').trim() === '' ? 'left blank' : 'not replaced';

      let reply: string;
      try {
        reply = await provider.complete(
          buildPrompt({
            field: describeField(path),
            document: slice.text,
            instruction: options.instruction ?? null,
          }),
        );
      } catch (error) {
        // The reason is read through the cause chain because Node's own fetch
        // throws `TypeError: fetch failed` and hides the useful half beneath it
        // -- a wrong address, a stopped model and an expired certificate
        // otherwise all arrive as the same two useless words. Putting it in a
        // note is only safe because of the redaction obligation on
        // `Completer`; read that before writing a second adapter.
        row.notes.push(
          `${path}: ${outcome} -- ${flatten(describeReason(error))}${sentClause(slice.shape)}`,
        );
        continue;
      }

      const cleaned = cleanReply(reply);
      if (cleaned.outcome !== 'ok') {
        // THREE DIFFERENT EVENTS, THREE DIFFERENT SENTENCES. "The model gave no
        // answer" is false for two of them: it answered, and this tool
        // discarded what it said. `cleanReply` writes the clause; repeating the
        // judgement here would be a second place for it to drift.
        row.notes.push(
          `${path}: ${outcome} -- ${cleaned.reason}.` +
            `${quoted(cleaned.discarded)}${sentClause(slice.shape)}`,
        );
        continue;
      }

      // THE MODEL PROPOSES; THE TOOL VERIFIES. Between a usable reply and a
      // written cell, and never anywhere else: a check that ran after the write
      // would be a flag rather than a guard, and this tool writes to a permanent
      // catalogue with no moderation queue.
      //
      // AGAINST `text`, THE WHOLE DOCUMENT, NOT `slice.text`. The model cannot
      // have read more than the slice, so a claim the rest of the file supports
      // is a coincidence rather than a fabrication -- and verifying the slice
      // would make a supported value depend on the character budget, so lowering
      // a setting would start refusing descriptions that had been fine.
      //
      // ALWAYS, WITH NO SETTING. This project has twice shipped a check that
      // reported success without running, and a switch is how that happens a
      // third time.
      const unsupported = unsupportedClaims(cleaned.text, text, profile);
      if (unsupported.length > 0) {
        // THE WHOLE VALUE, never part of it. Stripping the offending clause
        // would leave a half-removed sentence that reads as complete while
        // meaning something different, and this tool does not edit generated
        // prose. Nothing else on the row moves either: no cell, no `sources`
        // entry, no `aiWritten` record -- which is what keeps the row counting
        // as needing review -- and `flagged` is left standing, because the
        // source's doubt has NOT been acted on.
        row.notes.push(
          `${refusalNote(path, outcome, unsupported)}` +
            `${quoted(cleaned.text)}${sentClause(slice.shape)}`,
        );
        continue;
      }

      const note = `${writtenNote(column, path)}${sentClause(slice.shape)}`;
      wroteSomething = true;
      row.cells[path] = cleaned.text;
      row.sources[path] = AI_SOURCE;
      row.notes.push(note);
      // The structural record. See `aiWritten` in types.ts: it is what lets a
      // counter separate "a model wrote here, as designed" from "this row has a
      // problem", and what stops a second pass paying for this cell again.
      // `factKind` is asked once, here, where the column is in hand and the
      // answer has already been computed to word the note. `review.ts` runs on
      // three surfaces, two of which hold a row and no profile, so it cannot ask
      // again -- and a second copy of this judgement would be free to disagree
      // with the sentence the operator is reading.
      row.aiWritten[path] = { note, factField: factKind(column) !== null };
      // The source's doubt has been acted on. Leaving it would keep the cell
      // eligible for ever, and the note it holds describes a value that is no
      // longer in the cell.
      delete row.flagged[path];
      // "Fill that cell in by hand" is now false -- the cell has content, and
      // the note just pushed already asks for it to be checked. Removed by the
      // string `rows.ts` itself produces rather than by matching a prefix, so
      // changing the wording cannot silently strand it.
      if (column.flagIfEmpty === true) {
        const stale = row.notes.indexOf(expectedButEmptyNote(path));
        if (stale !== -1) row.notes.splice(stale, 1);
      }
    }

    if (wroteSomething) discloseInItem(row, profile, options.model);
  }
}

/**
 * Record in the ITEM that a model wrote something on this row, where the profile
 * asks for it.
 *
 * ## The only disclosure that survives the upload
 *
 * Everything else this module writes goes into `_notes`, and `plan.ts` drops
 * every annotation column before anything is contributed. So a cataloguer
 * reviewing the spreadsheet sees the flags and a future reader of the catalogue
 * sees none of them. This writes into an ordinary metadata column, which is
 * uploaded like any other -- at BYU-Idaho, beside the "Scanned to PDF" that
 * records the previous machine transformation of the same document.
 *
 * ## Once per row, never once per written cell
 *
 * A row with two enabled columns would otherwise carry the same sentence twice
 * in one field, and a profile with eight would carry it eight times, in a record
 * nobody can tidy afterwards without going back into openEQUELLA. The sentence
 * says a model wrote something here; saying it twice adds nothing and reads as a
 * bug to whoever finds it.
 *
 * ## Nothing written means nothing disclosed
 *
 * A refusal, a failed call, an empty slice and a row the cap stopped all leave
 * the row exactly as they found it, so there is nothing to disclose and the
 * field is not touched. A note claiming a model contributed to a record it never
 * saw is a false statement in a permanent catalogue -- and it would appear on
 * every row of a batch whose endpoint was down.
 *
 * ## The path was a real column at LOAD time, and that is not the same as now
 *
 * `parseProfile` refuses an `aiProvenance` whose path is not a declared,
 * writable column, because `csv.ts` builds the sheet from `profile.columns` and
 * anything written elsewhere is silently dropped. Being a column is also what
 * puts the path through `validateAgainstSchema` with every other one -- which is
 * the entire schema check, and the reason this function needs no schema. It
 * could not have one: `src/core/extract/` never touches the network.
 *
 * BUT THE PROFILE THAT REACHES HERE HAS NOT NECESSARILY BEEN THROUGH THE
 * LOADER SINCE. The desktop's column editor rewrites it in memory --
 * `removeColumn` returns `{ ...profile, columns: filtered }` and carries
 * `aiProvenance` forward untouched -- and `extractRun` never re-parses. Delete
 * the provenance column in the editor and run, and the loader's guarantee is a
 * statement about a profile that no longer exists: the disclosure would be
 * written into `row.cells`, dropped by `csv.ts`, and the ONE output of this
 * feature that survives the upload would be silently gone. Exactly the failure
 * `checkProvenance` was built to prevent, arriving through the one door it
 * cannot cover.
 *
 * `columns.ts#removeColumn` now drops an `aiProvenance` that names the column
 * being removed, which closes it at the source. This checks anyway, and says so
 * in `_notes` rather than writing into nothing, because "the loader guaranteed
 * it" is precisely the reasoning that was wrong the first time.
 */
function discloseInItem(row: ExtractedRow, profile: Profile, model: string): void {
  const provenance = profile.aiProvenance;
  if (provenance === undefined) return;

  // The same two exclusions `checkProvenance` applies, asked of the profile
  // actually in hand. `composeOnly` is dropped from the sheet by `csv.ts`, so a
  // column that has become one is as good as absent.
  const column = profile.columns.find((c) => c.path === provenance.path);
  if (column === undefined || column.composeOnly === true) {
    row.notes.push(
      `A language model wrote a value on this row, and the note recording that was to go in ` +
        `'${provenance.path}' -- but this profile has no such column any more, so it could not be ` +
        `written and will not reach openEQUELLA. Add the column back, or remove "aiProvenance" ` +
        `from the profile.`,
    );
    return;
  }

  // `parseProfile` has already refused any other placeholder, so a literal
  // brace surviving to here is one the loader passed and this substitution is
  // total.
  const note = provenance.append.replace(/\{model\}/g, model);
  const existing = (row.cells[provenance.path] ?? '').trim();
  // Joined rather than replacing: the field is a provenance field, and whatever
  // is already in it -- "Scanned to PDF" -- is a true statement about the same
  // document that must not be destroyed to make room for this one.
  row.cells[provenance.path] = existing === '' ? note : `${existing}; ${note}`;

  // RECORDED LIKE ANY OTHER FILLED CELL. `_source` is how a reviewer sorts a
  // spreadsheet to read only what this pass touched, and a cell that changed
  // without appearing there reads as one the document supplied. Not `AI_SOURCE`:
  // no model wrote this text -- the profile did, and the tool stamped it.
  row.sources[provenance.path] = PROVENANCE_SOURCE;

  // "Fill that cell in by hand" is now false: it has content. Cleared for the
  // same reason and by the same means as the model's own writes above -- by the
  // string `rows.ts` produces, never by matching a prefix.
  if (column.flagIfEmpty === true) {
    const stale = row.notes.indexOf(expectedButEmptyNote(provenance.path));
    if (stale !== -1) row.notes.splice(stale, 1);
  }
}

/**
 * The field, in words, for the prompt. `MWDL/deathDate` -> "a death date".
 *
 * The leaf only: a schema xpath is a path to a value and the last segment is
 * what the value is. Separators become spaces and camel case is split, because
 * "a deathdate" is not a phrase in the language the model is answering in.
 *
 * THE ARTICLE IS CHOSEN, not fixed at "a". `a abstract` in the first line of a
 * prompt is a small thing that says the tool is careless, to a reader who is
 * being asked to be careful.
 *
 * A COUPLING WORTH KNOWING: `prompt.ts`'s preamble stripper only recognises a
 * model announcing a `description`, `summary`, `answer` or `response`. A field
 * whose leaf is none of those -- `abstract`, `coverage` -- can still draw
 * "Here is the abstract:" and it will not be stripped. That is deliberate on
 * that side (an unusual preamble surviving is the accepted cost, a first line
 * wrongly removed is not) and is recorded here because this function is where
 * the vocabulary is decided.
 */
function describeField(path: string): string {
  const leaf = path.split('/').pop() ?? path;
  const words = leaf
    .replace(/[_-]+/g, ' ')
    // deathDate -> death Date, and ISBNNumber -> ISBN Number.
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .trim()
    .toLowerCase();
  return `${/^[aeiou]/.test(words) ? 'an' : 'a'} ${words}`;
}
