// tests/ai/pass.test.ts
import { describe, it, expect, vi } from 'vitest';
import {
  assertUsableModelPass,
  runModelPass,
  type ModelPassSettings,
} from '../../src/core/ai/pass.js';
import { modelSections } from '../../src/core/ai/fill.js';
import { ApiError } from '../../src/core/errors.js';
import type { DocumentData, ExtractedRow, Profile } from '../../src/core/extract/types.js';

/**
 * `pass.ts` is the seam between "an operator configured a model" and "documents
 * leave the machine", and NOTHING referenced it directly. Three mutations
 * survived a full run because of it -- one of them writing a broken sentence
 * into every item at any institution that configures `aiProvenance`:
 *
 *   model: settings.model  ->  model: ''      "Description generated by "
 *   instruction: profile.aiInstruction ?? null  ->  null
 *   sections: modelSections(profile)  ->  []
 *
 * All three are wiring: each reads something off the settings or the profile and
 * hands it to `fillWithModel`. `fill.ts` is thoroughly tested on what it does
 * with those values and had no way to notice that nothing was supplying them.
 */

const PROSE =
  'This obituary records what the family said about a long life in a small town, ' +
  'and what the college meant to it. ';

const LONG_WITH_SECTION = [
  PROSE.repeat(6),
  'Abstract',
  'ABSTRACTMARK the body of the abstract states the finding in one line.',
  'Keywords',
  'reading, undergraduates, libraries',
].join('\n');

const doc = (text: string): DocumentData => ({
  text,
  hasTextLayer: true,
  properties: {},
  tables: [],
});

const row = (over: Partial<ExtractedRow> = {}): ExtractedRow => ({
  cells: { 'MWDL/description': '' },
  sources: {},
  notes: [],
  flagged: {},
  aiWritten: {},
  ...over,
});

const SETTINGS: ModelPassSettings = {
  baseUrl: 'https://api.example.com/v1',
  model: 'gpt-4o-mini',
  apiKey: 'sk-secret',
  budget: 8000,
  cap: 10,
};

/** A fetch that answers every call and remembers what it was asked. */
function spy(content = 'A description.') {
  const bodies: string[] = [];
  const impl = vi.fn(async (_input: string | URL, init?: RequestInit) => {
    bodies.push(String(init?.body ?? ''));
    return new Response(JSON.stringify({ choices: [{ message: { content } }] }), { status: 200 });
  }) as unknown as typeof fetch;
  return { bodies, impl };
}

/** The prompt inside the first request, as the endpoint received it. */
const promptIn = (body: string): string =>
  (JSON.parse(body) as { messages: { content: string }[] }).messages[0]!.content;

const profile: Profile = {
  version: 1,
  pattern: '{name}.pdf',
  columns: [{ path: 'MWDL/description', sources: [{ ai: true }] }],
};

describe('runModelPass wiring', () => {
  /**
   * THE ONE THAT WRITES INTO A PERMANENT RECORD. `FillOptions.model` exists
   * because "a profile that asks 'generated by {model}' and is handed nothing
   * discloses 'generated by ', which is worse than not disclosing at all" --
   * and until this test, nothing checked that anything supplied it.
   */
  it('discloses the model that was actually configured', async () => {
    const { impl } = spy();
    const withProvenance: Profile = {
      ...profile,
      columns: [
        { path: 'MWDL/description', sources: [{ ai: true }] },
        { path: 'MWDL/conversionSpecifications', sources: [] },
      ],
      aiProvenance: {
        path: 'MWDL/conversionSpecifications',
        append: 'Description generated by {model}',
      },
    };
    const target = {
      row: row({ cells: { 'MWDL/description': '', 'MWDL/conversionSpecifications': '' } }),
      doc: doc(PROSE),
    };
    await runModelPass([target], withProvenance, SETTINGS, impl);
    expect(target.row.cells['MWDL/conversionSpecifications']).toBe(
      'Description generated by gpt-4o-mini',
    );
  });

  /** The model name reaches the request body too -- the endpoint has to be told
   *  which model to run, and an empty one fails after the document has been sent. */
  it('names the model in the request', async () => {
    const { bodies, impl } = spy();
    await runModelPass([{ row: row(), doc: doc(PROSE) }], profile, SETTINGS, impl);
    expect(JSON.parse(bodies[0]!).model).toBe('gpt-4o-mini');
  });

  /** The template's house style. Without it the model writes in whatever shape
   *  it likes and the collection's own form is silently abandoned. */
  it('carries the profile house style into the prompt', async () => {
    const { bodies, impl } = spy();
    const styled: Profile = {
      ...profile,
      aiInstruction: 'Write one line in this form: Died <date>; Born <date>.',
    };
    await runModelPass([{ row: row(), doc: doc(PROSE) }], styled, SETTINGS, impl);
    expect(promptIn(bodies[0]!)).toContain('Died <date>; Born <date>.');
  });

  it('sends no house style when the profile declares none', async () => {
    const { bodies, impl } = spy();
    await runModelPass([{ row: row(), doc: doc(PROSE) }], profile, SETTINGS, impl);
    expect(promptIn(bodies[0]!)).not.toContain('Died <date>');
  });

  /**
   * The section headings the profile already declares reach the slice. A
   * document over budget is cut to its opening plus named sections; with an
   * empty list the abstract is simply lost, and nothing anywhere says so.
   */
  it('prefers the sections the profile names when a document will not fit', async () => {
    const { bodies, impl } = spy();
    const sectioned: Profile = {
      version: 1,
      pattern: '{name}.pdf',
      columns: [
        { path: 'MWDL/summary', sources: [{ section: 'Abstract' }] },
        { path: 'MWDL/description', sources: [{ ai: true }] },
      ],
    };
    await runModelPass(
      [{ row: row(), doc: doc(LONG_WITH_SECTION) }],
      sectioned,
      { ...SETTINGS, budget: 400 },
      impl,
    );
    expect(promptIn(bodies[0]!)).toContain('ABSTRACTMARK');
  });

  it('does not invent a section the profile never named', async () => {
    const { bodies, impl } = spy();
    await runModelPass(
      [{ row: row(), doc: doc(LONG_WITH_SECTION) }],
      profile,
      { ...SETTINGS, budget: 400 },
      impl,
    );
    expect(promptIn(bodies[0]!)).not.toContain('ABSTRACTMARK');
  });

  it('honours the configured budget', async () => {
    const { bodies, impl } = spy();
    await runModelPass(
      [{ row: row(), doc: doc(LONG_WITH_SECTION) }],
      profile,
      { ...SETTINGS, budget: 300 },
      impl,
    );
    // The fence holds the slice; a budget of 300 cannot produce a 6000-character
    // prompt whatever else is in it.
    expect(promptIn(bodies[0]!).length).toBeLessThan(1500);
  });

  it('honours the configured cap', async () => {
    const { impl } = spy();
    const rows = [1, 2, 3].map(() => ({ row: row(), doc: doc(PROSE) }));
    await runModelPass(rows, profile, { ...SETTINGS, cap: 2 }, impl);
    expect(impl).toHaveBeenCalledTimes(2);
    expect(rows[2]!.row.notes.join(' ')).toMatch(/limit of 2/);
  });

  /** Empty means "no key", not "a key of length zero" -- the local case. */
  it('sends no Authorization header when the key is blank', async () => {
    let headers: Record<string, string> = {};
    const impl = vi.fn(async (_i: string | URL, init?: RequestInit) => {
      headers = Object.fromEntries(new Headers(init?.headers).entries());
      return new Response(JSON.stringify({ choices: [{ message: { content: 'x' } }] }), {
        status: 200,
      });
    }) as unknown as typeof fetch;
    await runModelPass(
      [{ row: row(), doc: doc(PROSE) }],
      profile,
      { ...SETTINGS, baseUrl: 'http://localhost:11434/v1', apiKey: '' },
      impl,
    );
    expect(headers['authorization']).toBeUndefined();
  });

  it('sends the key when there is one', async () => {
    let headers: Record<string, string> = {};
    const impl = vi.fn(async (_i: string | URL, init?: RequestInit) => {
      headers = Object.fromEntries(new Headers(init?.headers).entries());
      return new Response(JSON.stringify({ choices: [{ message: { content: 'x' } }] }), {
        status: 200,
      });
    }) as unknown as typeof fetch;
    await runModelPass([{ row: row(), doc: doc(PROSE) }], profile, SETTINGS, impl);
    expect(headers['authorization']).toBe('Bearer sk-secret');
  });
});

/**
 * `modelSections` reads the headings the profile already declares rather than
 * asking for them again. A second setting would be one more box to fill in
 * correctly, empty on every profile written before it existed, and free to drift
 * out of step with the sources beside it.
 */
describe('modelSections', () => {
  it('collects every section a profile names', () => {
    const p: Profile = {
      version: 1,
      pattern: '{n}.pdf',
      columns: [
        { path: 'a', sources: [{ section: 'Abstract' }, { opening: true }] },
        { path: 'b', sources: [{ section: 'Summary' }] },
      ],
    };
    expect(modelSections(p)).toEqual(['Abstract', 'Summary']);
  });

  it('deduplicates, so a document is sliced the same way twice', () => {
    const p: Profile = {
      version: 1,
      pattern: '{n}.pdf',
      columns: [
        { path: 'a', sources: [{ section: 'Abstract' }] },
        { path: 'b', sources: [{ section: 'Abstract' }] },
      ],
    };
    expect(modelSections(p)).toEqual(['Abstract']);
  });

  it('is empty for a profile that names none', () => {
    expect(modelSections(profile)).toEqual([]);
  });
});

/**
 * ## The pre-flight, and why it builds the real provider
 *
 * A configuration fault affects every row identically, so discovering it on row
 * one means the folder has already been walked and read -- and on the CLI it
 * means the confirmation the operator was asked to agree to was rendered from
 * the bad values. Every check here is therefore the one that would actually have
 * run, not a copy of it: the class is constructed and discarded.
 */
describe('assertUsableModelPass', () => {
  it('accepts settings a run would accept', () => {
    expect(() => assertUsableModelPass(SETTINGS)).not.toThrow();
  });

  it('refuses an address that is not a usable model endpoint', () => {
    expect(() => assertUsableModelPass({ ...SETTINGS, baseUrl: 'not a url' })).toThrow(ApiError);
  });

  /** The rule that stops a bearer key crossing the network in clear. Asked here
   *  so it is answered before a document is read, not on the first row. */
  it('refuses a key over plain http to somewhere that is not this machine', () => {
    expect(() =>
      assertUsableModelPass({ ...SETTINGS, baseUrl: 'http://models.example.edu/v1' }),
    ).toThrow(/not encrypted|clear text/i);
  });

  it('allows plain http to loopback, which every local runtime serves', () => {
    expect(() =>
      assertUsableModelPass({ ...SETTINGS, baseUrl: 'http://localhost:11434/v1', apiKey: '' }),
    ).not.toThrow();
  });

  it('refuses a time limit the provider could not honour', () => {
    expect(() => assertUsableModelPass({ ...SETTINGS, timeoutMs: 0 })).toThrow();
  });

  /** It opens no socket -- a pre-flight that contacted the endpoint would be a
   *  request the operator has not yet agreed to. */
  it('contacts nothing', () => {
    const impl = vi.fn();
    globalThis.fetch = impl as unknown as typeof fetch;
    assertUsableModelPass(SETTINGS);
    expect(impl).not.toHaveBeenCalled();
  });
});
